name: Compile Minecraft Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build --stacktrace

    - name: Ensure directory exists
      run: mkdir -p build/libs

    - name: List files in build/libs
      run: ls -l build/libs || echo "No files in build/libs"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: MinecraftMod
        path: build/libs/*.jar