name: Compile Minecraft Mod

on:
  push:
    branches: [ main ]  # 或你的默认分支
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Generate Gradle Wrapper
      run: ./gradlew wrapper --gradle-version 7.4  # 指定你需要的 Gradle 版本

    - name: Compile with Gradle
      run: ./gradlew build

    - name: Ensure directory exists
      run: mkdir -p build/libs

    - name: List files in build/libs
      run: ls -l build/libs || echo "No files in build/libs"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: MinecraftMod
        path: build/libs/