name: Compile Minecraft Mod

on:
  push:
    branches: [ main ]  # 或你的默认分支
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: actions/upload-artifact@v4

    - name: Compile with Gradle
      run: ./gradlew build

    - name: Ensure directory exists
      run: mkdir -p build/libs

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MinecraftMod
        path: build/libs/
